### ISSUE TITLE
Center alignment of the elements in the form.

### ISSUE THREAD

**Issue by 5hirish** [5hirish/adam_app#2]
Unable to align the input text to center. No need to align the checkbox to center.
The image below highlights the element to be aligned center to the card in a red rectangle.
![screenshot from 2016-10-26 13-45-12](https://cloud.githubusercontent.com/assets/7095496/19718876/f3d5727a-9b84-11e6-87e2-3dbbfdf51590.png)

**Comment by akshayvinchurkar** [comment]
1st of all put all your tab menu in to native menu

**Comment by 5hirish** [comment]
Another thing you don't have to execute the whole electron app to fix the issue. Just check the index.html file and fix that.

**Comment by akshayvinchurkar** [comment]
hmm

**Comment by 5hirish** [comment]
Send me a pull request.
